# Generated by Django 4.0.4 on 2022-07-21 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='text',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('raw_text', models.CharField(max_length=10000)),
                ('summary', models.CharField(max_length=1000)),
                ('labels', models.CharField(max_length=1000)),
            ],
        ),
    ]
