# Generated by Django 3.2.15 on 2022-08-06 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('text_summarization', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='text',
            name='preprocessed_data',
            field=models.CharField(default=' ', max_length=1000),
            preserve_default=False,
        ),
    ]
